# Generated by Django 3.2.6 on 2025-10-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('estadoActual', models.CharField(choices=[('transito', 'Transito'), ('alistamiento', 'Alistamiento'), ('por_verificar', 'Por Verificar'), ('rehazado_x_verificar', 'Rechazado por Verificar'), ('verificado', 'Verificado'), ('creado', 'Creado'), ('empacado_x_despachar', 'Empacado por Despachar'), ('despachado', 'Despachado'), ('despachado_x_facturar', 'Despachado por Facturar'), ('facturado', 'Facturado'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('produccion', 'Produccion'), ('bordado', 'Bordado'), ('dropshipping', 'Dropshipping'), ('compra', 'Compra'), ('anulado', 'Anulado')], default='alistamiento', max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('total', models.FloatField()),
            ],
        ),
    ]
