# Generated by Django 3.2.6 on 2025-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20251015_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estadoActual',
            field=models.CharField(choices=[('Transito', 'Transito'), ('Alistamiento', 'Alistamiento'), ('Por Verificar', 'Por Verificar'), ('Rechazado por Verificar', 'Rehazado X Verificar'), ('Verificado', 'Verificado'), ('Creado', 'Creado'), ('Empacado por Despachar', 'Empacadp X Despachar'), ('Despachado', 'Despachado'), ('Despachado por Facturar', 'Despachado X Facturar'), ('Facturado', 'Facturado'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Produccion', 'Produccion'), ('Bordado', 'Bordado'), ('Dropshipping', 'Dropshipping'), ('Compra', 'Compra'), ('Anulado', 'Anulado')], default='Alistamiento', max_length=50),
        ),
    ]
